name: "autoware"
N: 20
integrator_step: 0.2
n_discs: 3

solver_settings:
  # solver: "acados" # acados or forces
  solver: "forces" # acados or forces
  floating_license: true
  enable_timeout: true
  init: 2 # 0 = cold start, 1 = centerer start, 2 = warm start with the selected primal variables
  use_sqp: false

debug_output: false

enable_output: true
control_frequency: 20
deceleration_at_infeasible: 1.0
max_obstacles: 4
max_obstacle_distance: 100.
robot_radius: 1.125
robot:
  # Should be this, but if I look in rviz, it is the ones below
  # length: 4.54
  # com_to_back: 1.1
  length: 4.8
  com_to_back: 0.95
  width: 2.25
obstacle_radius: 1.0 #1.0 #0.4

linearized_constraints:
  add_halfspaces: 2 # For road constraints

road:
  two_way: false
  width: 10.0

shift_previous_solution_forward: false # Was true

contouring:
  num_segments: 6
  preview: 2.0 # [s], use 0.0 to disable preview

t-mpc:
  use_t-mpc++: true
  enable_constraints: true

probabilistic:
  enable: true
  risk: 0.05
  propagate_uncertainty: true

weights:
  goal: 10.
  velocity: 0.05 #0.5
  acceleration: 0.2
  angular_velocity: 5.0 # Note: Large increase to improve smoothness of steering #0.25 #0.05
  reference_velocity: 3.0 #1.5
  contour: 0.05 #0.01
  lag: 0.02 #0.2
  preview: 5.0
  slack: 1000.

# Copied from Prius: https://github.com/oscardegroot/lmpcc/blob/prius/lmpcc/cfg/PredictiveController_Prius.cfg
# Variable weights are not normalized
#
# weights:
#   goal: -1.
#   velocity: 0.05
#   acceleration: 0.2
#   angular_velocity: 0.5
#   reference_velocity: 5.0
#   contour: 0.03
#   lag: 0.2
#   slack: -1.

visualization:
  draw_every: 5 # stages
