name: "jackal"
N: 20
integrator_step: 0.05

# solver: "acados" # acados or forces
solver: "forces" # acados or forces

control_frequency: 20
num_obstacles: 3
obstacle_radius: 0.725

weights:
  goal: 5.
  velocity: 0.02
  acceleration: 0.05
  rotational_velocity: 2. #0.05

reference_velocity: 0.5
