name: "jackal"
N: 30 #20
integrator_step: 0.2
n_discs: 1

solver_settings:
  # solver: "acados" # acados or forces
  solver: "forces" # acados or forces
  floating_license: false
  enable_timeout: true
  init: 2 # 0 = cold start, 1 = centerer start, 2 = warm start with the selected primal variables
  use_sqp: false

debug_output: false
debug_limits: false

enable_output: true
control_frequency: 20
deceleration_at_infeasible: 3.0
max_obstacles: 12 # (solver)
robot_radius: 0.325
robot:
  length: 0.65
  width: 0.65
  com_to_back: 0.0
obstacle_radius: 0.4

linearized_constraints:
  add_halfspaces: 2  # (solver)

scenario_constraints:
  parallel_solvers: 1

road:
  two_way: false
  width: 6.0

shift_previous_solution_forward: false

contouring:
  num_segments: 3
  preview: 0.0
  add_road_constraints: true

t-mpc:
  use_t-mpc++: true
  enable_constraints: true

probabilistic:
  enable: true
  risk: 0.05
  propagate_uncertainty: true

# weights:
#   goal: 10.
#   velocity: 0.5 #0.5
#   acceleration: 0.15
#   angular_velocity: 0.25 #0.05
#   reference_velocity: 2.0 #1.5
#   contour: 0.5 #0.01
#   preview: 0.0
#   lag: 0.1
#   slack: 10000.

weights:
  goal: 10.
  velocity: 0.55
  acceleration: 0.34
  angular_velocity: 0.85
  reference_velocity: 2.0
  contour: 0.05
  preview: 0.0
  lag: 0.75
  slack: 10000.

visualization:
  draw_every: 5 # stages