# This is a basic workflow to help you get started with Actions
name: Test Solver Generation Package

# Controls when the workflow will run
on: 
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  basic:
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

       #----------------------------------------------
      #       load cached venv if cache exists
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      #----------------------------------------------
      # install dependencies if cache does not exist
      #----------------------------------------------
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      # install your root project, if required
      #----------------------------------------------
      - name: Install library
        run: poetry install --no-interaction
          
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      # Runs a set of commands using the runners shell
      - name: Run pytest
        run: PYTHONPATH=src/ poetry run python -m pytest mpc-planner-solver-generator/test/ --cov-report=xml:mpc-planner-solver-generator/coverage.xml --cov-config=mpc-planner-solver-generator/test/.coveragerc --cov --cov-fail-under=70

      #----------------------------------------------
      #              report results with badge
      #----------------------------------------------
      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        id: coverageComment
        with:
          pytest-xml-coverage-path: ./mpc-planner-solver-generator/coverage.xml
          title: Solver Generation
          badge-title: mpc-planner-solver-generator
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          unique-id-for-comment: python3.8.10
      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          gistID: 5e90d640f8c212ab7bbac38f72323f80
          filename: pytest-coverage-comment__main.json
          label: Coverage Report
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python
